# Generated by Django 2.2.1 on 2019-05-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(choices=[('NA', 'NONE'), ('M', 'MORNING'), ('A', 'AFTERNOON'), ('N', 'NIGHT')], max_length=50)),
                ('arrival', models.CharField(choices=[('NA', 'NONE'), ('M', 'MORNING'), ('A', 'AFTERNOON'), ('N', 'NIGHT')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='api.Day')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='api.Day')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='api.Day')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='api.Day')),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='api.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(choices=[('UFRN', 'Universidade Federal do Rio Grande do Norte'), ('IFRN', 'IFRN'), ('UNP', 'UNIFACEX'), ('NASSAU', 'NASSAU'), ('ESTACIO', 'ESTACIO'), ('CT-GAS', 'CT-GAS'), ('OUTRO', 'Outro')], max_length=200)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Schedule')),
            ],
        ),
    ]
