# Generated by Django 2.2.1 on 2019-05-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(choices=[('UFRN', 'Universidade Federal do Rio Grande do Norte'), ('IFRN', 'IFRN'), ('UNP', 'UNIFACEX'), ('NASSAU', 'NASSAU'), ('ESTACIO', 'ESTACIO'), ('CT-GAS', 'CT-GAS'), ('OUTRO', 'Outro')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_id', models.IntegerField(choices=[(2, 'SEGUNDA'), (3, 'TERCA'), (4, 'QUARTA'), (5, 'QUINTA'), (6, 'SEXTA')], unique=True)),
                ('departure', models.CharField(choices=[('NA', 'NONE'), ('M', 'MORNING'), ('A', 'AFTERNOON'), ('N', 'NIGHT')], max_length=50)),
                ('arrival', models.CharField(choices=[('NA', 'NONE'), ('M', 'MORNING'), ('A', 'AFTERNOON'), ('N', 'NIGHT')], max_length=50)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.Student')),
            ],
        ),
    ]
